// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw_D1G5W8rv-amJax_0xuEXlBeacq57vU',
    appId: '1:313359061224:web:e3eb5836f422167b7db95d',
    messagingSenderId: '313359061224',
    projectId: 'snooker-management-39520',
    authDomain: 'snooker-management-39520.firebaseapp.com',
    storageBucket: 'snooker-management-39520.appspot.com',
    measurementId: 'G-28S8TFGH3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh84fW2gYhTqqb_XTMaJyxe3NC-2Ob_EA',
    appId: '1:313359061224:android:f90b5f199fcfa17b7db95d',
    messagingSenderId: '313359061224',
    projectId: 'snooker-management-39520',
    storageBucket: 'snooker-management-39520.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqLtRlxBTVsYIXFDectY5UmJoS5Q9Mtlk',
    appId: '1:313359061224:ios:b408b2395e39e3667db95d',
    messagingSenderId: '313359061224',
    projectId: 'snooker-management-39520',
    storageBucket: 'snooker-management-39520.appspot.com',
    iosBundleId: 'com.example.snookerManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqLtRlxBTVsYIXFDectY5UmJoS5Q9Mtlk',
    appId: '1:313359061224:ios:b408b2395e39e3667db95d',
    messagingSenderId: '313359061224',
    projectId: 'snooker-management-39520',
    storageBucket: 'snooker-management-39520.appspot.com',
    iosBundleId: 'com.example.snookerManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw_D1G5W8rv-amJax_0xuEXlBeacq57vU',
    appId: '1:313359061224:web:a0e554186b778e3b7db95d',
    messagingSenderId: '313359061224',
    projectId: 'snooker-management-39520',
    authDomain: 'snooker-management-39520.firebaseapp.com',
    storageBucket: 'snooker-management-39520.appspot.com',
    measurementId: 'G-Z2X93ZT3JP',
  );

}